name: Node.js App CI

on:
  push:
    branches: [main]

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Run Node.js App
        run: node app.js
